
TOTAL_POSTPARTUM_DAYS = 42
PREPOSTPARTUM_DURATION_DAYS = 7
POSTPARTUM_DURATION_DAYS = TOTAL_POSTPARTUM_DAYS - PREPOSTPARTUM_DURATION_DAYS
PREPOSTPARTUM_DURATION_RATIO = PREPOSTPARTUM_DURATION_DAYS / TOTAL_POSTPARTUM_DAYS
POSTPARTUM_DURATION_RATIO = POSTPARTUM_DURATION_DAYS / TOTAL_POSTPARTUM_DAYS

